// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package functions

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
	"github.com/GuanceCloud/terraform-provider-guance/internal/sdk"
)

// functionResourceModel maps the resource schema data.
type functionResourceModel struct {
	ID          types.String `tfsdk:"id"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Title       types.String `tfsdk:"title"`
	Description types.String `tfsdk:"description"`
	FuncId      types.String `tfsdk:"func_id"`
}

// GetId returns the ID of the resource.
func (m *functionResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *functionResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *functionResourceModel) GetResourceType() string {
	return consts.TypeNameFunction
}

// SetCreatedAt sets the creation time of the resource.
func (m *functionResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
} // functionDataSourceModel maps the resource schema data.
type functionDataSourceModel struct {
	Items      []*functionResourceModel `tfsdk:"items"`
	Filters    []*sdk.Filter            `tfsdk:"filter"`
	MaxResults types.Int64              `tfsdk:"max_results"`
	ID         types.String             `tfsdk:"id"`
}
