// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package pipeline

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
)

// pipelineResourceModel maps the resource schema data.
type pipelineResourceModel struct {
	ID        types.String   `tfsdk:"id"`
	CreatedAt types.String   `tfsdk:"created_at"`
	Name      types.String   `tfsdk:"name"`
	Source    []types.String `tfsdk:"source"`
	Content   types.String   `tfsdk:"content"`
	TestData  types.String   `tfsdk:"test_data"`
	IsForce   types.Bool     `tfsdk:"is_force"`
	Category  types.String   `tfsdk:"category"`
	IsDefault types.Bool     `tfsdk:"is_default"`
}

// GetId returns the ID of the resource.
func (m *pipelineResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *pipelineResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *pipelineResourceModel) GetResourceType() string {
	return consts.TypeNamePipeline
}

// SetCreatedAt sets the creation time of the resource.
func (m *pipelineResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
}
