// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package pipeline

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var resourceSchema = schema.Schema{
	Description:         "Pipeline",
	MarkdownDescription: resourceDocument,
	Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "Numeric identifier of the order.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},

		"created_at": schema.StringAttribute{
			Description: "Timestamp of the last Terraform update of the order.",
			Computed:    true,
		},

		"name": schema.StringAttribute{
			Description: "Name",
			Required:    true,
		},

		"source": schema.ListAttribute{
			Description: "Data source list",

			Optional:    true,
			ElementType: types.StringType,
		},

		"content": schema.StringAttribute{
			Description: "Pipeline file content",
			Required:    true,
		},

		"test_data": schema.StringAttribute{
			Description: "Test data",

			Optional: true,
		},

		"is_force": schema.BoolAttribute{
			Description: "Is Force Overwrite",

			Optional: true,
		},

		"category": schema.StringAttribute{
			Description: "Category",
			Required:    true,
		},

		"is_default": schema.BoolAttribute{
			Description: "Is Default Pipeline",

			Optional: true,
		},
	},
}
