default: install

generate:
	go generate ./...

docs:
	./scripts/generate-docs.sh

check-docs: docs
	@if [ "`git status --porcelain docs/`" ]; then \
		git diff -- docs/; \
		echo "Uncommitted changes were detected in the autogenerated docs folder. Please run 'make docs' and commit the changes."; \
		echo "`git status --porcelain docs/`"; \
		echo ""; \
		echo "HINT: tfplugindocs uses the terraform binary on PATH to introspect the provider schema."; \
		echo "      Active terraform: `terraform version 2>/dev/null | head -1 || echo 'not found on PATH'`"; \
		exit 1; \
	else \
		echo "Success: No generated documentation changes detected"; \
	fi

install:
	go install .

test:
	go test -count=1 -parallel=4 ./...

testacc:
	TF_ACC=1 go test -count=1 -parallel=4 -timeout 10m -v ./...

.PHONY: check-docs default docs generate install test testacc
