// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package dashboard

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
)

// dashboardResourceModel maps the resource schema data.
type dashboardResourceModel struct {
	ID        types.String `tfsdk:"id"`
	CreatedAt types.String `tfsdk:"created_at"`
	Name      types.String `tfsdk:"name"`
	Manifest  types.String `tfsdk:"manifest"`
}

// GetId returns the ID of the resource.
func (m *dashboardResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *dashboardResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *dashboardResourceModel) GetResourceType() string {
	return consts.TypeNameDashboard
}

// SetCreatedAt sets the creation time of the resource.
func (m *dashboardResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
}
