// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package monitor

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
)

// monitorResourceModel maps the resource schema data.
type monitorResourceModel struct {
	ID          types.String `tfsdk:"id"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Manifest    types.String `tfsdk:"manifest"`
	AlertPolicy *AlertPolicy `tfsdk:"alert_policy"`
	Dashboard   *Dashboard   `tfsdk:"dashboard"`
}

// GetId returns the ID of the resource.
func (m *monitorResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *monitorResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *monitorResourceModel) GetResourceType() string {
	return consts.TypeNameMonitor
}

// SetCreatedAt sets the creation time of the resource.
func (m *monitorResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
}

// AlertPolicy maps the resource schema data.
type AlertPolicy struct {
	Id types.String `tfsdk:"id"`
}

// Dashboard maps the resource schema data.
type Dashboard struct {
	Id types.String `tfsdk:"id"`
}
