// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package mute

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
)

// muteResourceModel maps the resource schema data.
type muteResourceModel struct {
	ID            types.String    `tfsdk:"id"`
	CreatedAt     types.String    `tfsdk:"created_at"`
	MuteRanges    []*MuteRange    `tfsdk:"mute_ranges"`
	Notify        *NotifyOptions  `tfsdk:"notify"`
	NotifyTargets []*NotifyTarget `tfsdk:"notify_targets"`
	Onetime       *OnetimeOptions `tfsdk:"onetime"`
	Repeat        *RepeatOptions  `tfsdk:"repeat"`
	MuteTags      []*Tag          `tfsdk:"mute_tags"`
}

// GetId returns the ID of the resource.
func (m *muteResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *muteResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *muteResourceModel) GetResourceType() string {
	return consts.TypeNameMute
}

// SetCreatedAt sets the creation time of the resource.
func (m *muteResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
}

// MuteRange maps the resource schema data.
type MuteRange struct {
	Type        types.String          `tfsdk:"type"`
	Monitor     *MuteRangeMonitor     `tfsdk:"monitor"`
	AlertPolicy *MuteRangeAlertPolicy `tfsdk:"alert_policy"`
}

// MuteRangeAlertPolicy maps the resource schema data.
type MuteRangeAlertPolicy struct {
	Id types.String `tfsdk:"id"`
}

// MuteRangeMonitor maps the resource schema data.
type MuteRangeMonitor struct {
	Id types.String `tfsdk:"id"`
}

// NotifyOptions maps the resource schema data.
type NotifyOptions struct {
	Message    types.String `tfsdk:"message"`
	BeforeTime types.String `tfsdk:"before_time"`
}

// NotifyTarget maps the resource schema data.
type NotifyTarget struct {
	Type         types.String              `tfsdk:"type"`
	MemberGroup  *NotifyTargetMemberGroup  `tfsdk:"member_group"`
	Notification *NotifyTargetNotification `tfsdk:"notification"`
}

// NotifyTargetMemberGroup maps the resource schema data.
type NotifyTargetMemberGroup struct {
	Id types.String `tfsdk:"id"`
}

// NotifyTargetNotification maps the resource schema data.
type NotifyTargetNotification struct {
	Id types.String `tfsdk:"id"`
}

// OnetimeOptions maps the resource schema data.
type OnetimeOptions struct {
	Start types.String `tfsdk:"start"`
	End   types.String `tfsdk:"end"`
}

// RepeatCrontabSet maps the resource schema data.
type RepeatCrontabSet struct {
	Min   types.String `tfsdk:"min"`
	Hour  types.String `tfsdk:"hour"`
	Day   types.String `tfsdk:"day"`
	Month types.String `tfsdk:"month"`
	Week  types.String `tfsdk:"week"`
}

// RepeatOptions maps the resource schema data.
type RepeatOptions struct {
	Start           types.String      `tfsdk:"start"`
	End             types.String      `tfsdk:"end"`
	CrontabDuration types.String      `tfsdk:"crontab_duration"`
	Expire          types.String      `tfsdk:"expire"`
	Crontab         *RepeatCrontabSet `tfsdk:"crontab"`
}

// Tag maps the resource schema data.
type Tag struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}
