// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package guance

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/alertpolicy"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/blacklist"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/dashboard"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/membergroup"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/monitor"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/mute"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/notification"
	"github.com/GuanceCloud/terraform-provider-guance/internal/resources/pipeline"
)

// Resources defines the resources implemented in the provider.
func (p *guanceProvider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		alertpolicy.NewAlertPolicyResource,
		blacklist.NewBlackListResource,
		dashboard.NewDashboardResource,
		membergroup.NewMemberGroupResource,
		monitor.NewMonitorResource,
		mute.NewMuteResource,
		notification.NewNotificationResource,
		pipeline.NewPipelineResource,
	}
}
