// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package consts

const (
	TypeNameAlertPolicy  = "AlertPolicy"
	TypeNameDashboard    = "Dashboard"
	TypeNameMember       = "Member"
	TypeNameMemberGroup  = "MemberGroup"
	TypeNameMonitor      = "Monitor"
	TypeNameMute         = "Mute"
	TypeNameNotification = "Notification"
	TypeNamePipeline     = "Pipeline"
)
