// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package members

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
	"github.com/GuanceCloud/terraform-provider-guance/internal/sdk"
)

// memberResourceModel maps the resource schema data.
type memberResourceModel struct {
	ID        types.String `tfsdk:"id"`
	CreatedAt types.String `tfsdk:"created_at"`
	Email     types.String `tfsdk:"email"`
	Role      types.String `tfsdk:"role"`
}

// GetId returns the ID of the resource.
func (m *memberResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *memberResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *memberResourceModel) GetResourceType() string {
	return consts.TypeNameMember
}

// SetCreatedAt sets the creation time of the resource.
func (m *memberResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
} // memberDataSourceModel maps the resource schema data.
type memberDataSourceModel struct {
	Items      []*memberResourceModel `tfsdk:"items"`
	Filters    []*sdk.Filter          `tfsdk:"filters"`
	MaxResults types.Int64            `tfsdk:"max_results"`
	ID         types.String           `tfsdk:"id"`
}
