// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package members

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var dataSourceSchema = schema.Schema{
	Description:         "Workspace Member",
	MarkdownDescription: resourceDocument,
	Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "The hasd id of the resource.",
			Computed:    true,
		},

		"max_results": schema.Int64Attribute{
			Description: "The max results count of the resource will be returned.",
			Optional:    true,
		},

		"filters": schema.ListNestedAttribute{
			Description: "The list of the resource",
			Optional:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						Description: "The filter path, represent as json path.",
						Required:    true,
					},

					"values": schema.ListAttribute{
						ElementType: types.StringType,
						Required:    true,
						Description: "The filter values",
					},
				},
			},
		},

		"items": schema.ListNestedAttribute{
			Description: "The list of the resource",
			Computed:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Description: "The Guance Resource Name (GRN) of cloud resource.",
						Computed:    true,
					},

					"created_at": schema.StringAttribute{
						Description: "The RFC3339/ISO8601 time string of resource created at.",
						Computed:    true,
					},

					"email": schema.StringAttribute{
						Description: "Email",

						Optional: true,
					},

					"role": schema.StringAttribute{
						Description: "Role",

						MarkdownDescription: `
		Role, value must be one of: *owner*, *wsAdmin*, *general*, *readOnly*, other value will be ignored.
		`,

						Optional: true,

						Validators: []validator.String{
							stringvalidator.OneOf("owner", "wsAdmin", "general", "readOnly"),
						},
					},
				},
			},
		},
	},
}
