// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package alertpolicy

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/GuanceCloud/terraform-provider-guance/internal/consts"
)

// alertPolicyResourceModel maps the resource schema data.
type alertPolicyResourceModel struct {
	ID            types.String   `tfsdk:"id"`
	CreatedAt     types.String   `tfsdk:"created_at"`
	Name          types.String   `tfsdk:"name"`
	SilentTimeout types.Int64    `tfsdk:"silent_timeout"`
	Statuses      []types.String `tfsdk:"statuses"`
	AlertTargets  []*AlertTarget `tfsdk:"alert_targets"`
}

// GetId returns the ID of the resource.
func (m *alertPolicyResourceModel) GetId() string {
	return m.ID.ValueString()
}

// SetId sets the ID of the resource.
func (m *alertPolicyResourceModel) SetId(id string) {
	m.ID = types.StringValue(id)
}

// GetResourceType returns the type of the resource.
func (m *alertPolicyResourceModel) GetResourceType() string {
	return consts.TypeNameAlertPolicy
}

// SetCreatedAt sets the creation time of the resource.
func (m *alertPolicyResourceModel) SetCreatedAt(t string) {
	m.CreatedAt = types.StringValue(t)
}

// AlertTarget maps the resource schema data.
type AlertTarget struct {
	Type         types.String        `tfsdk:"type"`
	Notification *TargetNotification `tfsdk:"notification"`
	MemberGroup  *TargetMemberGroup  `tfsdk:"member_group"`
}

// TargetMemberGroup maps the resource schema data.
type TargetMemberGroup struct {
	Id types.String `tfsdk:"id"`
}

// TargetNotification maps the resource schema data.
type TargetNotification struct {
	Id types.String `tfsdk:"id"`
}
