// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package alertpolicy

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var resourceSchema = schema.Schema{
	Description:         "Alert Policy",
	MarkdownDescription: resourceDocument,
	Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "The Guance Resource Name (GRN) of cloud resource.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},

		"created_at": schema.StringAttribute{
			Description: "The RFC3339/ISO8601 time string of resource created at.",
			Computed:    true,
		},

		"name": schema.StringAttribute{
			Description: "Alert Policy Name",

			Required: true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},

		"silent_timeout": schema.StringAttribute{
			Description: "Silent timeout timestamp",

			Optional: true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},

		"statuses": schema.ListAttribute{
			Description: "The status value of the event to be sent",

			Required:    true,
			ElementType: types.StringType,
			PlanModifiers: []planmodifier.List{
				listplanmodifier.RequiresReplace(),
			},
		},

		"alert_targets": schema.ListNestedAttribute{
			Description: "Alert Action",

			Optional: true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: schemaAlertTarget,
			},
		},
	},
}

// schemaAlertTarget maps the resource schema data.
var schemaAlertTarget = map[string]schema.Attribute{
	"type": schema.StringAttribute{
		Description: "Alert type",

		MarkdownDescription: `
		Alert type, value must be one of: *member_group*, *notification*, other value will be ignored.
		`,
		Required: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.RequiresReplace(),
		},
		Validators: []validator.String{
			stringvalidator.OneOf("member_group", "notification"),
		},
	},

	"notification": schema.SingleNestedAttribute{
		Description: "Notification",

		Optional:   true,
		Attributes: schemaTargetNotification,
	},

	"member_group": schema.SingleNestedAttribute{
		Description: "Member Group",

		Optional:   true,
		Attributes: schemaTargetMemberGroup,
	},
}

// schemaTargetMemberGroup maps the resource schema data.
var schemaTargetMemberGroup = map[string]schema.Attribute{
	"id": schema.StringAttribute{
		Description: "Member Group",

		Required: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.RequiresReplace(),
		},
	},
}

// schemaTargetNotification maps the resource schema data.
var schemaTargetNotification = map[string]schema.Attribute{
	"id": schema.StringAttribute{
		Description: "Notification",

		Required: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.RequiresReplace(),
		},
	},
}
