// Code generated by Guance Cloud Code Generation Pipeline. DO NOT EDIT.

package alertpolicy

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var resourceSchema = schema.Schema{
	Description:         "Alert Policy",
	MarkdownDescription: resourceDocument,
	Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "Numeric identifier of the order.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},

		"created_at": schema.StringAttribute{
			Description: "Timestamp of the last Terraform update of the order.",
			Computed:    true,
		},

		"name": schema.StringAttribute{
			Description: "Alert Policy Name",
			Required:    true,
		},

		"silent_timeout": schema.Int64Attribute{
			Description: "Silent timeout timestamp",

			Optional: true,
		},

		"statuses": schema.ListAttribute{
			Description: "The status value of the event to be sent",
			Required:    true,
			ElementType: types.StringType,
		},

		"alert_targets": schema.ListNestedAttribute{
			Description: "Alert Action",

			Optional: true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: schemaAlertTarget,
			},
		},
	},
}

// schemaAlertTarget maps the resource schema data.
var schemaAlertTarget = map[string]schema.Attribute{
	"type": schema.StringAttribute{
		Description: "Alert type",
		Required:    true,
	},

	"notification": schema.SingleNestedAttribute{
		Description: "Notification",

		Optional:   true,
		Attributes: schemaTargetNotification,
	},

	"member_group": schema.SingleNestedAttribute{
		Description: "Member Group",

		Optional:   true,
		Attributes: schemaTargetMemberGroup,
	},
}

// schemaTargetMemberGroup maps the resource schema data.
var schemaTargetMemberGroup = map[string]schema.Attribute{
	"id": schema.StringAttribute{
		Description: "Member Group",
		Required:    true,
	},
}

// schemaTargetNotification maps the resource schema data.
var schemaTargetNotification = map[string]schema.Attribute{
	"id": schema.StringAttribute{
		Description: "Notification",
		Required:    true,
	},
}
